-- Create the DEMOGRPAHIC TABLE
CREATE TABLE PCORI_CDMV3.DEMOGRAPHIC (	
  PATID          VARCHAR(50), 
  BIRTH_DATE     DATE, 
  BIRTH_TIME     CHAR(5), 
  SEX            VARCHAR(2), 
  HISPANIC       VARCHAR(2), 
  RACE           CHAR(2), 
  BIOBANK_FLAG   CHAR(1), 
  RAW_SEX        VARCHAR,
  RAW_HISPANIC   VARCHAR,
  RAW_RACE       VARCHAR
);


-- Insert from ESP to demographic table
INSERT INTO  PCORI_CDMV3.DEMOGRAPHIC (
  PATID,
  BIRTH_DATE,
  RAW_SEX,
  RAW_RACE,
  RAW_HISPANIC
)
SELECT 
  mrn,                 /*  as number */
  date_of_birth,       /*  as 1919-10-04 */
  gender,              /* as M,F or UNKNOWN */
  race,                /* */
  ethnicity            /* as hispanic and non-hispanic */
FROM PUBLIC.emr_patient;


-- Gender
UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET SEX = 'UN'
WHERE RAW_SEX='UNKNOWN';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET SEX = 'F'
WHERE RAW_SEX='F';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET SEX = 'M'
WHERE RAW_SEX='M';

-- Hispanic
UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET HISPANIC = 'Y'
WHERE RAW_HISPANIC='Hispanic';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET HISPANIC = 'N'
WHERE RAW_HISPANIC='Non-Hispanic';

-- Race
UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '03'
WHERE RAW_RACE='Black';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '02'
WHERE RAW_RACE='Indian';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '04'
WHERE RAW_RACE='Native Hawaiians';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '05'
WHERE RAW_RACE='White';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '06'
WHERE RAW_RACE='Multiracial';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = 'OT'
WHERE RAW_RACE='Other';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '01'
WHERE RAW_RACE='Native American';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = 'UN'
WHERE RAW_RACE='UNKNOWN';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = 'UN'
WHERE RAW_RACE='Hispanic';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '02'
WHERE RAW_RACE='Asian';

UPDATE PCORI_CDMV3.DEMOGRAPHIC
SET RACE = '01'
WHERE RAW_RACE='Alaskan';
