--
CREATE TABLE PCORI_CDMV3.PROCEDURES (
  PROCEDURESID   VARCHAR(50),
  PATID           VARCHAR(50),
  ENCOUNTERID     VARCHAR(50),
  ENC_TYPE        CHAR(2),
  ADMIT_DATE      DATE,
  PROVIDERID      VARCHAR(50),
  PX              VARCHAR(18),
  PX_TYPE         CHAR(2),
  PX_SOURCE       CHAR(2),
  RAW_PX          VARCHAR,
  RAW_PX_TYPE     VARCHAR,
  RAW_PX_SOURCE   VARCHAR
);


-- INSERT THE INFO AND GENERATE A FAKE KEY
INSERT INTO PCORI_CDMV3.PROCEDURES (
  PROCEDURESID,
  PATID,
  ENCOUNTERID,
  ENC_TYPE,
  ADMIT_DATE,
  PROVIDERID,
  PX,
  PX_TYPE,
  PX_SOURCE
)

SELECT
  CAST ((md5(random()::text || clock_timestamp()::text)::uuid) AS VARCHAR), 
  EMR_ENCOUNTER.MRN                       AS PATID,
  EMR_ENCOUNTER.ID                        AS ENCOUNTERID,
  'AV'                                    AS ENC_TYPE,
  EMR_ENCOUNTER.DATE                      AS ADMIT_DATE,
  EMR_ENCOUNTER.PROVIDER_ID               AS PROVIDERID,
  EMR_ENCOUNTER_ICD9_CODES.ICD9_ID        AS PX,
  '09'                                    AS PX_TYPE,
  'UN'                                    AS PX_SOURCE
FROM PUBLIC.EMR_ENCOUNTER_ICD9_CODES
LEFT JOIN ESP_ICD9_STAGE
ON EMR_ENCOUNTER_ICD9_CODES.ICD9_ID = ESP_ICD9_STAGE.ICD9_ID
LEFT JOIN ICD9_SG
ON ESP_ICD9_STAGE.CODE = ICD9_SG.CODE
LEFT JOIN EMR_ENCOUNTER
LEFT JOIN
STATIC_ICD9 
ON EMR_ENCOUNTER_ICD9_CODES.ICD9_ID = STATIC_ICD9.CODE
LEFT JOIN ICD9_SG
ON STATIC_ICD9.NAME = ICD9_SG.NAME
ON EMR_ENCOUNTER_ICD9_CODES.ENCOUNTER_ID = EMR_ENCOUNTER.ID
WHERE ICD9_SG.NAME IS NOT NULL;



INSERT INTO PCORI_CDMV3.PROCEDURES (
  PROCEDURESID,
  PATID,
  ENCOUNTERID,
  ENC_TYPE,
  ADMIT_DATE,
  PROVIDERID,
  PX,
  PX_TYPE,
  PX_SOURCE
)
SELECT
  CAST ((md5(random()::text || clock_timestamp()::text)::uuid) AS VARCHAR), 
  EMR_ENCOUNTER.MRN                       AS PATID,
  EMR_ENCOUNTER.ID                        AS ENCOUNTERID,
  'AV'                                    AS ENC_TYPE,
  EMR_ENCOUNTER.DATE                      AS ADMIT_DATE,
  EMR_ENCOUNTER.PROVIDER_ID               AS PROVIDERID,
  EMR_ENCOUNTER_ICD9_CODES.ICD9_ID        AS PX,
  '09'                                    AS PX_TYPE,
  'UN'                                    AS PX_SOURCE
FROM EMR_ENCOUNTER_ICD9_CODES
LEFT JOIN
STATIC_ICD9 
ON EMR_ENCOUNTER_ICD9_CODES.ICD9_ID = STATIC_ICD9.CODE
LEFT JOIN ICD9_SG
ON STATIC_ICD9.NAME = ICD9_SG.NAME
LEFT JOIN EMR_ENCOUNTER
ON EMR_ENCOUNTER_ICD9_CODES.ENCOUNTER_ID = EMR_ENCOUNTER.ID
WHERE ICD9_SG.NAME IS NOT NULL;
