
COPY PCORI_CDMV3.DEMOGRAPHIC
TO '/tmp/demographic.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.ENCOUNTER
TO '/tmp/encounter.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.DIAGNOSIS
TO '/tmp/diagnosis.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.PROCEDURES
TO '/tmp/procedures.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.LAB_RESULT_CM
TO '/tmp/lab_result_cm.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.PRESCRIBING
TO '/tmp/prescribing.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.ENROLLMENT
TO '/tmp/enrollment.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.VITAL
TO '/tmp/vital.csv'
DELIMITER ',' CSV
HEADER;
