
COPY PCORI_CDMV3.DEMOGRAPHIC
FROM '/tmp/demographic.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.ENCOUNTER
FROM '/tmp/encounter.csv'
DELIMITER',' CSV
HEADER;

COPY PCORI_CDMV3.DIAGNOSIS
FROM '/tmp/diagnosis.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.PROCEDURES
FROM '/tmp/procedures.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.LAB_RESULT_CM
FROM '/tmp/lab_result_cm.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.PRESCRIBING
FROM '/tmp/prescribing.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.ENROLLMENT
FROM '/tmp/enrollment.csv'
DELIMITER ',' CSV
HEADER;

COPY PCORI_CDMV3.VITAL
FROM '/tmp/vital.csv'
DELIMITER ',' CSV
HEADER;
